### ISSUE TITLE
Outline approaches for P. meandrina functional annotation and decide if update functional annotation

### ISSUE THREAD

**Issue by hputnam** [urol-e5/deep-dive#10]
https://academic.oup.com/gigascience/article/doi/10.1093/gigascience/giac098/6815755

http://cyanophora.rutgers.edu/Pocillopora_meandrina/

**Comment by sr320** [comment]
@daniellembecker @JillAshey update on this?

**Comment by hputnam** [comment]
@daniellembecker @JillAshey update on this?

**Comment by daniellembecker** [comment]
Discussed at 20240308 meeting, no immediate need for P. meandrina functional annotation for the descriptive ncRNAs paper
