### ISSUE TITLE
Annotation gtf available for P verucosa?

### ISSUE THREAD

**Issue by sr320** [urol-e5/deep-dive#11]
Can someone point me to this if available?

**Comment by AHuffmyer** [comment]
@daniellembecker functional annotation is here: https://github.com/hputnam/Becker_E5/tree/master/Functional_Annotation

**Comment by kubu4** [comment]
Notebook here detailing GTF conversion from source GFF :https://robertslab.github.io/sams-notebook/2023/01/27/Data-Wrangling-P.verrucosa-Genome-GFF-to-GTF-Using-gffread.html

**Comment by sr320** [comment]
thanks
