### ISSUE TITLE
Trimming for sRNA-seq data

### ISSUE THREAD

**Issue by kubu4** [urol-e5/deep-dive#14]
After trimming the sRNA-seq data with my usual workflow, I ended up with reads that were still 150bp in length. This didn't seem right, considering the library prep protocol indicates that miRNAs should be ~21bp and piRNAs should be ~31bp...

So, I ran a very quick trimming comparison for people to view and weigh in on.

Please review and post thoughts on how we should handle this data.

I used [`flexbar`](https://github.com/seqan/flexbar) for trimming, as it was listed in the [NEBNext® Multiplex Small RNA Library Prep Set for Illumina](https://www.neb.com/-/media/nebus/files/manuals/manuale7300_e7330_e7560_e7580.pdf?rev=d0964a2e637843b1afcb9f7d666d07b2&hash=5B733FC9B41103A865143C75D0F3FC5D) (PDF) manual for trimming parameters.

---

### Adapter trimming only

![FastQC plot of Per Base Sequence Content of read with only adapter trimming. Shows the presence of poly-G (black line) at end of reads. Also shows persistance of 150bp read lengths, despite trimming.](https://github.com/RobertsLab/sams-notebook/blob/master/images/screencaps/20230524-E5-coral-sRNAseq_trimmings_comparisons-adapter_trim_only-fastqc_screenshot.png.png?raw=true)

FastQC of adapter trim _only_ still shows read lengths of 150bp. Additionally, the bulk of the 3' end of the reads show extensive poly-G signals. Admittedly, [`flexbar`](https://github.com/seqan/flexbar) doesn't have a default poly-G trimming option. However, using [`fastp`](https://github.com/OpenGene/fastp), which does have a poly-G trimming option, still showed similar results (data not shown - not comparing trimmers, just highlighting persistence of long reads).

---
### Adapter and length trimming

![FastQC plot of Per Base Sequence Content of read with adapter trimming and trimming to a length of 50bp (from the 3' end). Shows elimination of 150bp reads and poly-G. Also shows an increase in heterogeneity (i.e. more drastic spikes in plots) after ~30bp.](https://github.com/RobertsLab/sams-notebook/blob/master/images/screencaps/20230524-E5-coral-sRNAseq_trimmings_comparisons-adapter_and_length_50-fastqc_screenshot.png?raw=true)

FastQC of adapter trim _and_ trimming to a length of 50bp (from the 3' end). As expected, performing length trimming removed all reads longer than 50bp, which also resulted in removal of poly-G sequence. Also shows an increase in heterogeneity (i.e. more drastic spikes in plots) after ~30bp. This is probably expected, as the [NEBNext® Multiplex Small RNA Library Prep Set for Illumina](https://www.neb.com/-/media/nebus/files/manuals/manuale7300_e7330_e7560_e7580.pdf?rev=d0964a2e637843b1afcb9f7d666d07b2&hash=5B733FC9B41103A865143C75D0F3FC5D) (PDF) manual indicates that miRNA should be ~21bp and piRNAs ~31bp. Thus, the sequence after that could be something else.

**Comment by kubu4** [comment]
@jarcasariego - @sr320 suggested pinging you to see if you had any input/feedback on the sRNA-seq trimming process.

**Comment by jarcasariego** [comment]
@kubu4 I used the pre-trimmed reads that the company sent me. This is what they described in the report, "The raw fastq files were initially processed using Cutadapt. Adapter sequences were removed and
reads were filtered based on length. Reads shorter than 5 bp are filtered first to determine RNA
degradation. Reads with a minimum 15 bp length are aligned to a reference. Table 1 shows the
Sequencing Metrics across each sample." 
However, they used their own kit so it might be a lot different to the NEB one.

**Comment by jarcasariego** [comment]
After trimming they were bi-modally distributed with a peak at 22-23 bp and another at 30 bp. They sequenced 1x75.

**Comment by kubu4** [comment]
Thanks again. Discussed at today's E5 molecular meeting, we'll go forward with 50bp lengths.

**Comment by kubu4** [comment]
Adding info here for posterity. I ended up trimming to 35bp lengths.

However, based on [results with ShortStack](https://github.com/urol-e5/deep-dive/issues/19 ) (miRNAs identified by ShortStack), and subsequent results (or, lack-thereof, in come cases) with BLASTn against miRBase/miRGeneDB, miRTrace, MirMachine, and mirdeep2, I'm starting to think that the trim length is too long. All of these programs expect sequence of lengths >17bp and <24bp.

So, I'm probably going to re-run trimming and then re-run these other programs and see if things improve.

However, knowing that sequence length is likely very important for miRNA analysis, why should trimming even be necessary (other than to remove adapters)? I.e. What is all of the "excess" sequence that's present in these sRNA libraries? Instead of trimming to a desired length, should I just trim adapters and then _filter_ sequences for those that are <=24bp?
