### ISSUE TITLE
Run short stack on DEF sRNA reads

### ISSUE THREAD

**Issue by sr320** [urol-e5/deep-dive#19]

**Comment by kubu4** [comment]
Alrighty, this is finished. I haven't had time to review what all the outputs are (and how to interpret them), but here are links to the two species output folders. Figured I'd at least get this posted so people could start looking at things, if they wanted:

_A.pulchra_: https://gannet.fish.washington.edu/Atumefaciens/20230628-E5_coral-ShortStack-sRNAseq/A_pulchra/ShortStack_out/

_P.meandrina_: https://gannet.fish.washington.edu/Atumefaciens/20230628-E5_coral-ShortStack-sRNAseq/P_meandrina/ShortStack_out/

Here's what output folder structure looks like:

![Screencap showing folder structure for ShortStack output.](https://github.com/urol-e5/deep-dive/assets/4514104/f22025c3-0e93-411b-b627-6971ad5f9a3d)

**Comment by kubu4** [comment]
Oh, and here's the script used to run ShortStack:

https://github.com/RobertsLab/sams-notebook/blob/master/sbatch_scripts/20230628-E5_coral-ShortStack-sRNAseq.sh

**Comment by sr320** [comment]
@kubu4 can you also please run for meandrina - https://github.com/urol-e5/deep-dive/wiki/Species-Characteristics-and-Genomic-Resources#pocillopora-meandrina

**Comment by kubu4** [comment]
Link is above.

**Comment by sr320** [comment]
SOrry - meant evermanni...

https://github.com/urol-e5/deep-dive/wiki/Species-Characteristics-and-Genomic-Resources#porites-evermanni

**Comment by kubu4** [comment]
Output directory is here:

https://gannet.fish.washington.edu/Atumefaciens/20230731-peve-E5_coral-ShortStack-sRNAseq/P_evermanni/ShortStack_out/
