### ISSUE TITLE
Develop gene expression count matrix

### ISSUE THREAD

**Issue by sr320** [urol-e5/deep-dive#2]

**Comment by AHuffmyer** [comment]
Analysis in progress (Jill & Ariana). Data downloaded from NCBI to URI Andromeda; [details in this post](https://ahuffmyer.github.io/ASH_Putnam_Lab_Notebook/E5-Deep-Dive-RNAseq-Count-Matrix-Analysis/).

**Comment by daniellembecker** [comment]
_Pocillopora verrucosa_  gene count matrix

https://github.com/hputnam/Becker_E5/blob/master/RAnalysis/Data/RNA-seq/P.verrucosa/Host/Poc_gene_count_matrix.csv

**Comment by AHuffmyer** [comment]
P. verrucosa Gene Count Matrix generated 4/5/2023 by Jill and Ariana 
https://github.com/urol-e5/deep-dive/blob/main/A-Pver/data/rna-seq/Pverr_gene_count_matrix.csv

Next step is for AH/JA to do preliminary analysis and compare results to Danielle's above ^.
