### ISSUE TITLE
Genome to use for A.pulchra analyses?

### ISSUE THREAD

**Issue by kubu4** [urol-e5/deep-dive#20]

**Comment by hputnam** [comment]
Steven mapped Apulchra reads to Amillipora, Ahycan, Adigitifera 
https://sr320.github.io/Apulcra/ 

A millipora has the highest mapping rates and the genome currently has the best assembly and annotation
https://www.science.org/doi/10.1126/science.aba4674
https://www.ncbi.nlm.nih.gov/bioproject/633778

**Comment by sr320** [comment]
current genome being used 

https://github.com/urol-e5/deep-dive/wiki/Species-Characteristics-and-Genomic-Resources#genomic-resources-1
