### ISSUE TITLE
Genome to use for P.evermanni analyses?

### ISSUE THREAD

**Issue by kubu4** [urol-e5/deep-dive#21]

**Comment by hputnam** [comment]
https://www.nature.com/articles/s41564-019-0532-4 
http://plut.reefgenomics.org/

**Comment by hputnam** [comment]
New Genomes released this week from corals in Moorea
https://genomebiology.biomedcentral.com/articles/10.1186/s13059-023-02960-7

**Comment by zbengt** [comment]
HISAT Alignments:
https://zbengt.github.io/2023-07-05-E5_3species_porites_mapping/
