### ISSUE TITLE
Genome to use for Pocillopora analyses?

### ISSUE THREAD

**Issue by hputnam** [urol-e5/deep-dive#22]
Test mapping against Pocillopora cf. effusa: https://www.genoscope.cns.fr/corals/genomes.html
https://genomebiology.biomedcentral.com/articles/10.1186/s13059-023-02960-7

The assembled genome of Pocillopora was assigned to SVD1 lineage based on genome-wide SNPs (Voolstra et al. in revision). The SVD1 lineage corresponds to GSH01 [[94](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-023-02960-7#ref-CR94)] and carries the mtORF marker type 2/11.

**Comment by hputnam** [comment]
Pocillopora cf. effusa colonies were collected in French Polynesia by the CRIOBE at Moorea.

**Comment by daniellembecker** [comment]
![Screen Shot 2023-06-23 at 10 07 36 AM](https://github.com/urol-e5/deep-dive/assets/40968353/a4c5e2de-ebb9-4112-805c-4a60d1d21dfd)
