### ISSUE TITLE
query on P evermanii sRNA

### ISSUE THREAD

**Issue by sr320** [urol-e5/deep-dive#28]
Looking at https://owl.fish.washington.edu/nightingales/P_evermanni/30-852430235/

why are there only 3 samples?  and

why did we do paired end sequencing?

**Comment by kubu4** [comment]
Don't know. We didn't do the experiment/sequencing. We'll need @hputnam to weigh in on this one.

**Comment by hputnam** [comment]
RE sample size: https://github.com/RobertsLab/resources/issues/1632#issuecomment-1549748008

RE small RNA sequencing, these were their recommendations: https://fs.hubspotusercontent00.net/hubfs/3478602/13002-SD-2%201221%20RNA-Seq%20Technical%20Specs%20Sell%20Sheet.pdf
