### ISSUE TITLE
Add lncRNA pipeline to repo

### ISSUE THREAD

**Issue by sr320** [urol-e5/deep-dive#30]

**Comment by zbengt** [comment]
Added full lncRNA discovery pipeline using A pluchra data:
https://github.com/urol-e5/deep-dive/blob/main/DEF-cross-species/code/05-lncRNA-discovery-overview.Rmd

Currently in a bit of a Frankenstein state, but will be updating to make it more push button

**Comment by sr320** [comment]
to clarify you mean millipora?
