### ISSUE TITLE
Add transcript fastas to wiki 

### ISSUE THREAD

**Issue by sr320** [urol-e5/deep-dive#34]
https://github.com/urol-e5/deep-dive/wiki/Species-Characteristics-and-Genomic-Resources

**Comment by shedurkin** [comment]
For P.evermanni, I'm pretty sure I have a functioning script to extract all the CDS lines from the gff, get fastas for each, and concatenate and label by parent! The only downside is it's quite slow (I don't know enough bash tricks to make it any more efficient) -- it's processed ~15% of the gff in the last hour, so it'll be running for the rest of the day. I'll let y'all know when it's done

**Comment by shedurkin** [comment]
Okie dokie, the [rendered code](https://github.com/urol-e5/deep-dive/blob/main/E-Peve/code/12-Peve-RNAseq-kallisto.md) for generating a transcriptome fasta (and running kallisto) for P.evermanni, and [the transcriptome fasta](https://github.com/urol-e5/deep-dive/blob/main/E-Peve/data/Porites_evermanni_CDS.fasta) itself are both pushed to the deep-dive repo!

**Comment by kubu4** [comment]
Nice work! Impressive.

I think your `.md` file didn't actually get re-rendered (commit is still from last week).

The HTML version got rendered, though:

https://htmlpreview.github.io/?https://github.com/urol-e5/deep-dive/blob/main/E-Peve/code/12-Peve-RNAseq-kallisto.html

I only glanced through the code, but figured I should ask this. Did you take into account that GFF files are 1-based (i.e. `start` is `1`) and BED files are 0-based (i.e. `start` is `0`)? Meaning, if using the GFF as input to `bedtools getfasta`, you should subtract `1` from the GFF coordinates so `bedtools` pulls out the proper sequence.

Admittedly, for alignment-free gene expression analysis, this is likely not an issue?

**Comment by shedurkin** [comment]
Hmm, i was just assuming that since the bedtools getfasta doc lists gff files as one of the accepted inputs it would distinguish bed and gff files and process them appropriately -- it sounds like that's not the case?

**Comment by shedurkin** [comment]
haha good point -- it should be straightforward to add a gff -> bed conversion before generating the transcriptome, it'll just take a while to rerun

**Comment by shedurkin** [comment]
I see [bedops](https://bedops.readthedocs.io/en/latest/content/reference/file-management/conversion/gff2bed.html) has a feature to convert gff to bed, and I saw in the [handbook](https://robertslab.github.io/resources/Genomic-Resources/#pocillipora-verrucosa) that it's been used before in the lab, but I don't see bedops in the /home/shared directory of tools on Raven -- is it stored somewhere else or would it need to be installed?

**Comment by kubu4** [comment]
I've gone ahead and installed bedops on Raven:

`/home/shared/bedops_linux_x86_64-v2.4.41/bin`

**Comment by zbengt** [comment]
Transcripts fastas for Pocillopora and Acropora are added to the wiki. Acropora is the transcripts fasta from NCBI (https://www.ncbi.nlm.nih.gov/datasets/genome/GCF_013753865.1/). Pocillopora is from the CDS on the Rutgers server (http://cyanophora.rutgers.edu/Pocillopora_meandrina/). These links are included in the wiki as well.

**Comment by sr320** [comment]
@shedurkin can you finish up by adding evermanni?

**Comment by shedurkin** [comment]
Added P.evermanni transcripts fasta, as well as links and download dates for original CDS gff and scaffolds fasta files and a link to the code used to generate the transcripts fasta: https://github.com/urol-e5/deep-dive/wiki/Species-Characteristics-and-Genomic-Resources#transcripts-1
