### ISSUE TITLE
Develop count matrix for transposable elements (copy number)

### ISSUE THREAD

**Issue by sr320** [urol-e5/deep-dive#4]

**Comment by sr320** [comment]
@kubu4 could you run RepeatMasker on Pver genome?

``
-species "all" : Sets species to all
-gff : Create GFF output file (in addition to default files)
```

**Comment by AHuffmyer** [comment]
Need to confirm correct genome to use before we can develop the count matrix

**Comment by hputnam** [comment]
@kubu4 We have chosen the P. meandrina genome.
