### ISSUE TITLE
Rerunning miRNA ID using merged reads

### ISSUE THREAD

**Issue by shedurkin** [urol-e5/deep-dive#40]
I'm going to continue rerunning the miRNA ID analyses using the merged sRNA reads while Sam is out. It looks like the current state of the analyses is:

- [x] A. pulchra -- ShortStack
- [x] A. pulchra -- MirDeep2
- [x] A. pulchra -- BLAST
- [x] P. evermanni -- ShortStack (getting errors)
- [x] P. evermanni -- MirDeep2
- [x] P. evermanni -- BLAST
- [x] P. meandrina -- ShortStack
- [x] P. meandrina -- MirDeep2
- [x] P. meandrina -- BLAST

Sam, if you have any corrections/updates/tips for proceeding with these, please just let me know!

**Comment by shedurkin** [comment]
Realized in meeting today that most of these also need to be rerun with Jill's cnidarian mirbase database

- [ ] A. pulchra -- ShortStack (cnidarian miRBase)
- [ ]  A. pulchra -- MirDeep2 (cnidarian miRBase)
- [ ]  A. pulchra -- BLAST (cnidarian miRBase)
- [ ]  P. evermanni -- ShortStack (getting errors) (cnidarian miRBase)
- [ ]  P. evermanni -- MirDeep2 (cnidarian miRBase)
- [ ]  P. evermanni -- BLAST (cnidarian miRBase)
- [ ]  P. meandrina -- ShortStack (cnidarian miRBase)
- [ ]  P. meandrina -- MirDeep2 (cnidarian miRBase)
- [ ]  P. meandrina -- BLAST (cnidarian miRBase)

**Comment by kubu4** [comment]
@shedurkin

So we don't end up duplicating efforts, I figured we should mention what we're working on.

I'm planning on handling the remaining _P.meandrina_ tasks this week.

**Comment by kubu4** [comment]
Actually, looks like you've taken care of _P.meandrina_ BLAST.

It doesn't look like you've started on MirDeep2, so I'll get that going momentarily.

**Comment by shedurkin** [comment]
ok it looks like _P.evermanni_ shortstack is the last thing that needs to be rerun. Any luck with debugging @kubu4? I tried it on my machine as a sanity check, and I'm getting the same error messages you noted in #39

**Comment by shedurkin** [comment]
I updated the manuscript results section with all of the merged reads results. @kubu4 when you get the chance could you add links to the outputs of analyses you ran?
