### ISSUE TITLE
Compare sequence similarity of mature miRNA across species and with database matches

### ISSUE THREAD

**Issue by sr320** [urol-e5/deep-dive#45]
Create a cladogram / PCA etc that shows grouping of mature miRNAs of three species with those matches in the database.

**Comment by sr320** [comment]
possible programs. 

For aligning short miRNA sequences and generating visualizations in R, you might consider the following packages:

Biostrings - This package from Bioconductor is excellent for handling biological sequences. It provides functions for reading, manipulating, and aligning short sequences, which is ideal for miRNA.

ShortRead - Also from Bioconductor, this package is tailored for handling high-throughput sequencing data, including short sequences like miRNAs. It includes functionality for quality assessment, alignments, and data visualization.

Gviz - For visualization, Gviz (from Bioconductor) is a great choice. It is designed for visualizing genomic data and can be very useful for displaying the results of miRNA alignments in a genomic context.

**Comment by sr320** [comment]
Note Need to include database hits too....

Can you provide links to mature miRNAs fastas for all three species. (3 files is fine)
Fasta file with database matches.

**Comment by sr320** [comment]
Another maybe more feasible:
for every mature miRNA provide the score and evalue for top hit in each of two other species.

(be sure to use short rna flag)

**Comment by shedurkin** [comment]
> Can you provide links to mature miRNAs fastas for all three species. (3 files is fine) Fasta file with database matches.

https://github.com/urol-e5/deep-dive/blob/main/DEF-cross-species/output/10-shortRNA-ShortStack-comparison/Apul_results_mature.txt
https://github.com/urol-e5/deep-dive/blob/main/DEF-cross-species/output/10-shortRNA-ShortStack-comparison/Peve_results_mature.txt
https://github.com/urol-e5/deep-dive/blob/main/DEF-cross-species/output/10-shortRNA-ShortStack-comparison/Pmea_results_mature.txt

**Comment by sr320** [comment]
Fastas, those are not fastas...

**Comment by shedurkin** [comment]
oops, here you go

Apul:
https://github.com/urol-e5/deep-dive/blob/main/DEF-cross-species/output/10-shortRNA-ShortStack-comparison/Apul_ShortStack_mature_annotated.fasta

Peve:
https://github.com/urol-e5/deep-dive/blob/main/DEF-cross-species/output/10-shortRNA-ShortStack-comparison/Peve_ShortStack_mature_annotated.fasta

Pmea:
https://github.com/urol-e5/deep-dive/blob/main/DEF-cross-species/output/10-shortRNA-ShortStack-comparison/Pmea_ShortStack_mature_annotated.fasta

**Comment by shedurkin** [comment]
completed, code rendered and pushed (https://github.com/urol-e5/deep-dive/blob/main/DEF-cross-species/code/10-shortRNA-ShortStack-comparison.md).

**Comment by sr320** [comment]
Lets still do this

> for every mature miRNA provide the score and evalue for top hit in each of two other species.

**Comment by shedurkin** [comment]
https://github.com/urol-e5/deep-dive/blob/main/DEF-cross-species/output/10-shortRNA-ShortStack-comparison/combined_blast.tab
Table of top blastn hits in each species for all individuals
