### ISSUE TITLE
Accidental commit/merge to main (in D-Apul)

### ISSUE THREAD

**Issue by shedurkin** [urol-e5/deep-dive#47]
Soooo I was trying to clean up my working directory and mistakenly caused a ["merge" ](https://github.com/urol-e5/deep-dive/commit/7da9f442109d6031aba35f792aad819d100b7669)-- Anyone have any idea how to revert a pushed change like this? Probably a good idea to not push/pull anything else until we do @kubu4 

Thanks in advance, apologies for any trouble this causes!

**Comment by kubu4** [comment]
There's nothing wrong with a merge.

Is it preventing you from doing anything (e.g. can't pull, can't push, etc)?

If not, then you're good to go!
