### ISSUE TITLE
Rename miRNAs

### ISSUE THREAD

**Issue by sr320** [urol-e5/deep-dive#48]

**Comment by JillAshey** [comment]
[Link](https://github.com/urol-e5/deep-dive/blob/main/DEF-cross-species/output/10-shortRNA-ShortStack-comparison/Apul_results_mature_named.csv) to Apul mature miRNAs w/ names

[Link](https://github.com/urol-e5/deep-dive/blob/main/DEF-cross-species/output/10-shortRNA-ShortStack-comparison/Peve_results_mature_named.csv) to Peve mature miRNAs w/ names

[Link](https://github.com/urol-e5/deep-dive/blob/main/DEF-cross-species/output/10-shortRNA-ShortStack-comparison/Pmea_results_mature_named.csv) to Pmea mature miRNAs w/ names

**Comment by kubu4** [comment]
Just to clarify - it looks like they haven't been renamed. Instead, a new column has been added (column 22):
 
- `given_miRNA_name`

Is my assessment accurate?

Also, could you please provide link to code for generating these files? I need to re-run ShortStack on one of the species and will need to perform this task.

Alternatively, would it be easy for you to update the cnidarian miRNA FastA? Then, we wouldn't need any additional downstream steps after ShortStack to handle renaming...

**Comment by JillAshey** [comment]
Yes I manually added the `given_miRNA_name` after looking at all of the files and the miRNAs that got hits to the databases.
