### ISSUE TITLE
Develop count matrix for long non-coding RNA

### ISSUE THREAD

**Issue by sr320** [urol-e5/deep-dive#5]

**Comment by sr320** [comment]
Are lncRNA already annotated in the genome?

**Comment by kubu4** [comment]
Nope:

```shell
awk -F"\t" '{print $3}' Pver_genome_assembly_v1.0.valid.gff3 | sort -u

CDS
exon
five_prime_UTR
gene
mRNA
three_prime_UTR
```

**Comment by sr320** [comment]
https://nf-co.re/lncpipe

**Comment by sr320** [comment]
@zbengt can you provide your workflow here for lncRNA discovery  (example code chunks for each step with annotation would be fine... )

**Comment by zbengt** [comment]
[Here](https://zbengt.github.io/2023-04-20-LncRNA-Discovery/) is a lab notebook post about it

**Comment by zbengt** [comment]
lncRNA count matrix [here](https://github.com/course-fish546-2023/zach-lncRNA/blob/main/output/filtered_count_matrix.tsv)
Repo [here](https://github.com/course-fish546-2023/zach-lncRNA) 
Workflow Rpub [here](https://rpubs.com/zbengt/coral-lncRNA-discovery)
