### ISSUE TITLE
Change Pocillopora meandrina to Pocillopora tuahiniensis in manuscript, figures, tables 

### ISSUE THREAD

**Issue by JillAshey** [urol-e5/deep-dive#50]
For the deep dive, _Pocillopora meandrina_ is actually _Pocillopora tuahiniensis_ from mtORF data. Please change any instances of _Pocillopora meandrina_ in the manuscript text, figures, tables, etc to _Pocillopora tuahiniensis_!

**Comment by hputnam** [comment]
We need to ensure this is just for all of our samples and NOT for the genome.

**Comment by daniellembecker** [comment]
Changed any instances of _Pocillopora meandrina_ in the manuscript text, figures, tables, etc to _Pocillopora tuahiniensis_, except for the genomic resources paragraph since _P. meandrina_ genome still being used as of now.

**Comment by shedurkin** [comment]
updated miRNA figures to correct species name and provided links to new figures in the paper
