### ISSUE TITLE
Azenta RNA/sRNA-seq - QC - response needed

### ISSUE THREAD

**Issue by kubu4** [urol-e5/deep-dive#55]
From Azenta:

> Comments: Hi Sam, I hope all is well. Please find attached the RNA QC results for your bulk RNA/small RNA projects with us, with results from Qubit and Tapestation. Please note, many the samples have RIN value less than 6.0, suggesting some signs of degradation (QC note 2). Some samples are also below 100ng of RNA, which is our suggested minimum for this type of library prep (QC note 1). These samples would obviously also fall below or suggested threshold for RNA amount for the miRNA workflow as well. Please let me know how you would like to proceed:
> 1. Continue as-is with our best effort. Please note, although we have extensive experience in working with less than optimal samples, we cannot guarantee results for ones that do not meet our minimum requirements.
> 2. Resubmit the samples.
> 3. Omit the samples from library prep.
> 4. Switch to rRNA depletion library prep, which is more indicated for degraded samples. Please note this would increase the cost of the project.
If you have any questions, please let me know. Upon your reply I will follow up accordingly with next steps. I look forward to hearing from you. If you would prefer to instead discuss over a call, please let me know and I will be happy to schedule a time with you.

QC reports are here (have requested TapeStation report for samples 1-80, which was not provided):

[Sample QC report of_30-1047560508_240828033818.pdf](https://github.com/user-attachments/files/16853374/Sample.QC.report.of_30-1047560508_240828033818.pdf)

[SampleQC_81-117_30-1047560508.pdf](https://github.com/user-attachments/files/16853375/SampleQC_81-117_30-1047560508.pdf)

@JillAshey - Let me know what you think and I'll let Azenta know.

**Comment by JillAshey** [comment]
Thanks Sam! I'll look over the QC info. Could you get a quote for how much it would cost for the rRNA depletion?

**Comment by JillAshey** [comment]
Notes to self: 
- All samples that received a 1 (not enough starting material) from Azenta QC were POR. Below is submission info for those samples.

| Plate | Well number | Azenta sample name | Colony ID | Timepoint | Sample Type\* | Species/Strain\*  | Sample Buffer\*        | Total Amount (ng)\* | Volume (µL) | Conc (ng/µL) |
| ----- | ----------- | ------------------ | --------- | --------- | ------------- | ----------------- | ---------------------- | ------------------- | ----------- | ------------ |
| 1     | F1          | 1F1                | POR-73    | TP2       | Total RNA     | Porites evermanni | DNAse/RNAse-free water | 0                   | 90          | 0            |
| 1     | H1          | 1H1                | POR-245   | TP3       | Total RNA     | Porites evermanni | DNAse/RNAse-free water | 1710                | 90          | 19           |
| 1     | E2          | 1E2                | POR-69    | TP3       | Total RNA     | Porites evermanni | DNAse/RNAse-free water | 1629                | 90          | 18.1         |
| 1     | H2          | 1H2                | POR-73    | TP4       | Total RNA     | Porites evermanni | DNAse/RNAse-free water | 1261.5              | 87          | 14.5         |
| 1     | B3          | 1B3                | POR-83    | TP3       | Total RNA     | Porites evermanni | DNAse/RNAse-free water | 1061.4              | 87          | 12.2         |
| 1     | F3          | 1F3                | POR-83    | TP2       | Total RNA     | Porites evermanni | DNAse/RNAse-free water | 1539.9              | 87          | 17.7         |
| 1     | G3          | 1G3                | POR-74    | TP3       | Total RNA     | Porites evermanni | DNAse/RNAse-free water | 1270.2              | 87          | 14.6         |
| 1     | C5          | 1C5                | POR-73    | TP3       | Total RNA     | Porites evermanni | DNAse/RNAse-free water | 1647                | 90          | 18.3         |
| 1     | B7          | 1B7                | POR-245   | TP2       | Total RNA     | Porites evermanni | DNAse/RNAse-free water | 2007                | 90          | 22.3         |
| 1     | E7          | 1E7                | POR-69    | TP4       | Total RNA     | Porites evermanni | DNAse/RNAse-free water | 2043                | 90          | 22.7         |
| 1     | F7          | 1F7                | POR-83    | TP4       | Total RNA     | Porites evermanni | DNAse/RNAse-free water | 1513.8              | 87          | 17.4         |
| 1     | C11         | 1C11               | POR-74    | TP4       | Total RNA     | Porites evermanni | DNAse/RNAse-free water | 3024                | 90          | 33.6         |
| 1     | D12         | 1D12               | POR-260   | TP2       | Total RNA     | Porites evermanni | DNAse/RNAse-free water | 2488.2              | 87          | 28.6         |
| 2     | D1          | 2D1                | POR-236   | TP1       | Total RNA     | Porites evermanni | DNAse/RNAse-free water | 1157.1              | 87          | 13.3         |
| 2     | E1          | 2E1                | POR-216   | TP3       | Total RNA     | Porites evermanni | DNAse/RNAse-free water | 1323                | 90          | 14.7         |
| 2     | D3          | 2D3                | POR-262   | TP3       | Total RNA     | Porites evermanni | DNAse/RNAse-free water | 1746                | 90          | 19.4         |
| 2     | E3          | 2E3                | POR-236   | TP2       | Total RNA     | Porites evermanni | DNAse/RNAse-free water | 2357.7              | 87          | 27.1         |

- We did not receive all of the tapestation results back yet. There were some discrepancies with the qubit vs tapestation concentrations  - those that did fail the qubit did not always fail the tapestation. Generally, it seems like Qubit is more reliable for concentration quantification, which is what Azenta used to make its QC determination of 'not enough starting material'. 

My initial thought would be to do rRNA depletion library prep, as that prep does better with degraded samples and we could get more lncRNA information via this method. However, it will be more expensive so waiting to hear what the price difference would be.

**Comment by kubu4** [comment]
QC Report for samples 1 - 80:

[SampleQC_1-80_30-1047560508_a3dde5ed-6929-4b1b-9d96-f8807097ad1f.pdf](https://github.com/user-attachments/files/16873082/SampleQC_1-80_30-1047560508_a3dde5ed-6929-4b1b-9d96-f8807097ad1f.pdf)


I'll email them to find out price difference to run rRNA depletion.

**Comment by hputnam** [comment]
@JillAshey Does this apply to both mRNA and small RNA? For example when the quantity is low, are they not going to be able to make either the mRNA or smallRNA libraries, or one but not the other?

**Comment by JillAshey** [comment]
@hputnam in my emails with Azenta, they said that they use 100ng of total RNA for standard RNAseq library prep and 500ng of total RNA for small RNAseq (provided that they do not have to redo anything or troubleshoot). So they need 600 ng total for both assays. 

All samples sent, except for 1 (POR-73 TP2), had >700ng of RNA when they were qubited at URI, either by Kristina or myself. Here's the spreadsheet [info](https://docs.google.com/spreadsheets/d/1iFsVfp1vix9IfNcqSajQfLgXXDg0CCPT/edit?gid=1648071810#gid=1648071810) with the samples we sent. 

When Azenta QCed the samples, they found 17 samples that did not pass their concentration threshold. They reported Nanodrop, Qubit and Tapestation concentrations but seem to determine 'too low' concentrations from the Qubit only.

**Comment by kubu4** [comment]
rRNA depletion (instead of polyA selection) will result in an _increase_ of $45/sample (from $175/sample to $220/sample).

This would be total increase in costs of `$5265`.

**Comment by JillAshey** [comment]
Azenta can proceed with polyA prep and sequencing with samples as is
