### ISSUE TITLE
GO functional enrichment for closest genes to ncRNAs 

### ISSUE THREAD

**Issue by JillAshey** [urol-e5/deep-dive#57]
I am looking at the functions of the genes that are closest to the ncRNAs for Apul, Peve, and Ptuh. 

Here's the R code for the 3 species that I have been using to examine the functions of the genes that are closest to ncRNAs: 
- [Apul](https://github.com/urol-e5/deep-dive/blob/main/D-Apul/code/19-bedtools-closest.Rmd)
- [Peve](https://github.com/urol-e5/deep-dive/blob/main/E-Peve/code/19-bedtools-closest.Rmd)
- [Ptuh](https://github.com/urol-e5/deep-dive/blob/main/F-Pmea/code/19-bedtools-closest.Rmd)

miRNA outputs: 
- [Apul miRNA closest gene](https://github.com/urol-e5/deep-dive/blob/main/D-Apul/output/19-bedtools-closest/Apul_mature_miRNAs_bedtools_annot.csv)
- [Peve miRNA closest gene](https://github.com/urol-e5/deep-dive/blob/main/E-Peve/output/19-bedtools-closest/Peve_mature_miRNAs_bedtools_annot.csv)
- [Ptuh miRNA closest gene](https://github.com/urol-e5/deep-dive/blob/main/F-Pmea/output/19-bedtools-closest/Pmea_mature_miRNAs_bedtools_annot.csv)

on my to do list: 
- Closest gene/mRNA to lncRNA and piRNA clusters 
- go enrichment for closest gene to ncRNAs 

I have looked into the closest gene to the piRNA clusters (see R code linked above). @jarcasariego also looked into this and made a figure for the manuscript that visualized the shared GO functional enrichment of genes overlapping piRNA clusters but I can't find the code to make this figure and am not sure what annotations he used. @jarcasariego could you send me the code that you used to make your GO enrichment figure on page 15 of the manuscript?

**Comment by jarcasariego** [comment]
Sorry, I forgot to push it after I finished. See the code at the end of this [R script](https://github.com/urol-e5/deep-dive/blob/main/DEF-cross-species/code/12-piRNA-comparizon.Rmd)
