### ISSUE TITLE
Develop workflow for DNA methylation level

### ISSUE THREAD

**Issue by sr320** [urol-e5/deep-dive#6]
Want to be able to look at loci, gene, and/or region

**Comment by sr320** [comment]
Here is a bismark workflow for getting loci level methylation at 5x and 10x. 
https://github.com/urol-e5/deep-dive/blob/main/A-Pver/code/00-bismark.sh

output: https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/021523-be/

**Comment by hputnam** [comment]
when we run this on samples, add several --score_min options to check for increasing mapping without increasing error (i.e., look for inflection point of %mapping to Chh or Chg to choose this 
)

**Comment by hputnam** [comment]
https://github.com/jarcasariego/ACER_clonal_divergence/blob/main/WGBS/code/20201209_Alignment_test_WGBS_ACER.sub

**Comment by hputnam** [comment]
This is generally ready for use as a workflow. As noted above it is best practice to check multiple mapping --score_min options to optimize choice for generating the final dataset.
