### ISSUE TITLE
Pver genome annotation file

### ISSUE THREAD

**Issue by sr320** [urol-e5/deep-dive#7]
We should make sure folks are using same files in terms of genome and annotation... 

Note
@kubu4 developed files at https://robertslab.github.io/resources/Genomic-Resources/#pocillipora-verrucosa

Which genome and annotation files?

**Comment by hputnam** [comment]
Add P. meandrina information to this summary
http://cyanophora.rutgers.edu/Pocillopora_meandrina/

**Comment by AHuffmyer** [comment]
Please add links to genome and annotation file that people are using

**Comment by kubu4** [comment]
Rutgers FastA:

-   [`Pver_genome_assembly_v1.0.fasta`](https://owl.fish.washington.edu/halfshell/genomic-databank/Pver_genome_assembly_v1.0.fasta) (363MB)

    -   MD5 checksum: `cb1ed5a1b724d92456347a28bb25f228`

    -   Downloaded 20230127: <http://pver.reefgenomics.org/download/>

-   [`Pver_genome_assembly_v1.0-hisat2-indices.tar.gz`](https://gannet.fish.washington.edu/Atumefaciens/20230131-pver-v1.0-hisat2-build-index/Pver_genome_assembly_v1.0-hisat2-indices.tar.gz) (tarball gzip; 594MB)

    -   MD5 checksum: `57e193e101396fab67de04c851f63240`

    -   Needs to be unpacked before use!

    -   Notebook: [Genome-Indexing-P.verrucosa-v1.0-Assembly-with-HiSat2-on-Mox.html](https://robertslab.github.io/sams-notebook/2023/01/31/Genome-Indexing-P.verrucosa-v1.0-Assembly-with-HiSat2-on-Mox.html)

-   [`Pver_genome_assembly_v1.0-valid.gff3`](https://gannet.fish.washington.edu/Atumefaciens/20230127-pver-gff_to_gtf/Pver_genome_assembly_v1.0-valid.gff3) (70MB)

    -   MD5 checksum: `5dd8f21a4faea1f46c48a5ab253749d7`

    -   Modified/validated version of `Pver_genome_assembly_v1.0.gff3`

    -   Created 20230127: [Data-Wrangling-P.verrucosa-Genome-GFF-to-GTF-Using-gffread](https://robertslab.github.io/sams-notebook/2023/01/27/Data-Wrangling-P.verrucosa-Genome-GFF-to-GTF-Using-gffread.html)

-   [`Pver_genome_assembly_v1.0-valid.gtf`](https://gannet.fish.washington.edu/Atumefaciens/20230127-pver-gff_to_gtf/Pver_genome_assembly_v1.0-valid.gtf) (48MB)

    -   MD5 checksum: `c3cc8fb576bcf39dd17b6d229100aa56`

    -   Created 20230127: [Data-Wrangling-P.verrucosa-Genome-GFF-to-GTF-Using-gffread](https://robertslab.github.io/sams-notebook/2023/01/27/Data-Wrangling-P.verrucosa-Genome-GFF-to-GTF-Using-gffread.html)
