### ISSUE TITLE
Compare quality of verracosa and meandrina genome

### ISSUE THREAD

**Issue by sr320** [urol-e5/deep-dive#8]

**Comment by hputnam** [comment]
P. meandrina functional annotation = 69.44%
P. verrucosa functional annotation = 96.83%

**Comment by AHuffmyer** [comment]
This is related to the de novo transcriptome issue in this repo

**Comment by hputnam** [comment]
Page 7 on Molecular Mechanism meeting notes: https://docs.google.com/document/d/1FBxuwh0VBiVplKs3_CEY_lGDt9wBIMhEgEJJVbpz5l4/edit#

Decision is to move forward with P. meandrina genome after functional reannotation
