### ISSUE TITLE
Compare de novo transcriptome assembly to different genome gene sets.

### ISSUE THREAD

**Issue by sr320** [urol-e5/deep-dive#9]

**Comment by hputnam** [comment]
We need to use the mTORF information to use only RNASeq data from a single species.

**Comment by hputnam** [comment]
Trinity or SPADES?

**Comment by jarcasariego** [comment]
Found this [blog](http://achri.blogspot.com/2017/02/transcriptome-analysis-without.html) with code for genome guided de-novo assembly with trinity
